language: objective-c
osx_image: xcode7.3
xcode_project: Relayout.xcodeproj
xcode_sdk: iphonesimulator9.3

env:
  global:
    - FRAMEWORK_NAME=Relayout

before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- xctool clean build -project Relayout.xcodeproj -scheme Relayout -sdk iphonesimulator
- xctool clean build -project Relayout.xcodeproj -scheme "Sample App" -sdk iphonesimulator
- xctool test -project Relayout.xcodeproj -scheme Relayout -sdk iphonesimulator
- carthage build --no-skip-current
- pod lib lint

before_deploy:
- carthage archive $FRAMEWORK_NAME

deploy:
  provider: releases
  api_key: "$GITHUB_API_KEY"
  file: 
    - "Relayout.framework.zip"
  skip_cleanup: true,
  on:
    repo: stevestreza/Relayout
    tags: true

