language: objective-c
osx_image: xcode7.3

before_install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- xctool clean build -project Relayout.xcodeproj -scheme Relayout -sdk iphonesimulator
- xctool test -project Relayout.xcodeproj -scheme Relayout -sdk iphonesimulator
